"""Initial AI service schema

Revision ID: c9a0e336d1ea
Revises: 
Create Date: 2026-01-13 19:02:37.469893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9a0e336d1ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embeddings', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_chunks_asset_id'), 'content_chunks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_content_chunks_course_id'), 'content_chunks', ['course_id'], unique=False)
    op.create_table('course_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('estimated_duration', sa.String(), nullable=True),
    sa.Column('content_insights', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('content_quality_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_analysis_course_id'), 'course_analysis', ['course_id'], unique=True)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_assets', sa.Integer(), nullable=True),
    sa.Column('processed_assets', sa.Integer(), nullable=True),
    sa.Column('failed_assets', sa.Integer(), nullable=True),
    sa.Column('total_chunks_created', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_asset_details', sa.JSON(), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_course_id'), 'processing_jobs', ['course_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_course_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_course_analysis_course_id'), table_name='course_analysis')
    op.drop_table('course_analysis')
    op.drop_index(op.f('ix_content_chunks_course_id'), table_name='content_chunks')
    op.drop_index(op.f('ix_content_chunks_asset_id'), table_name='content_chunks')
    op.drop_table('content_chunks')
    # ### end Alembic commands ###